README.md, api/v1alpha1/k6_types.go, pkg/resources/jobs/runner.go
Support for overriding the k6 image. Suggested by @dgzlopes  in https://github.com/k6io/operator/issues/15#issuecomment-848648427
=> Support for overriding the k6 image

config/rbac/leader_election_role.yaml
=> remove configmap/status resource from leader-election-role

pkg/resources/jobs/runner.go, pkg/resources/jobs/runner_test.go, pkg/resources/jobs/starter.go
Signed-off-by: Hans Knecht <Hans.Knecht@missionlane.com>
=> fix: update images to use ones with scuttle

pkg/resources/jobs/helpers.go, pkg/resources/jobs/runner_test.go, pkg/resources/jobs/starter_test.go
=> fix: change istio to disable by default in runner

.github/workflows/e2e-test.yaml
The workflow was a bit outdated and with small bugs which are fixed here.
=> Fix for e2e-test workflow in CI

controllers/k6_initialize.go
=> Always inspect test run to rely on duration estimate

pkg/resources/jobs/initializer.go, pkg/resources/jobs/initializer_test.go
Details in https://github.com/grafana/k6-operator/issues/172
=> Revert removal of annotations from initializer

Dockerfile.runner, README.md
Signed-off-by: Paul Balogh <javaducky@gmail.com>
=> Correct k6 image name and prometheus environment variable

pkg/resources/jobs/initializer.go, pkg/resources/jobs/initializer_test.go
=> Store archived script to /tmp in initializer

Makefile
Fixes https://github.com/grafana/k6-operator/issues/231
=> Bump kubebuilder-tools-version in tests

.github/workflows/e2e-test.yaml, .github/workflows/push.yaml, Makefile, config/manager/kustomization.yaml, config/manifests/bases/k6-operator.clusterserviceversion.yaml, pkg/resources/jobs/initializer.go, pkg/resources/jobs/initializer_test.go, pkg/resources/jobs/runner.go, pkg/resources/jobs/runner_test.go, pkg/resources/jobs/starter.go
=> Update image names to k6-operator over generic operator

controllers/plz_controller.go
Fixes lack of clean up upon deletion of PLZ resource.
=> Clean deletion of PLZ CRD

.github/workflows/helm-release.yaml, charts/Chart.yaml, charts/cr.yaml, charts/ct.yaml
=> Add CI for Helm release

README.md
kustomize is needed for `make bundle`.
=> docs: add kustomize to prerequisites

api/v1alpha1/zz_generated.deepcopy.go, controllers/k6_create.go
=> Duplicate job is an error only after wait period

charts/cr.yaml
=> Helm: generated release notes

.github/workflows/e2e-test.yaml, .github/workflows/golangci-lint.yaml, .github/workflows/helm-lint.yaml, .github/workflows/helm-test.yaml, .github/workflows/unit-test.yaml, .github/workflows/yamllint.yaml
Dependencies specific for Helm are postponed for now.
=> CI: update and unify versions of dependencies

.github/workflows/helm-test.yaml, charts/ct.yaml
Related issue: https://github.com/grafana/k6-operator/issues/419
=> CI: fix `ct install` execution and add config options

.github/workflows/helm-lint.yaml, .github/workflows/helm-test.yaml
Related issue: https://github.com/grafana/k6-operator/issues/419
=> CI: bump chart-testing-action

charts/k6-operator/samples/customAnnotationsAndLabels.yaml
The sample values file for the chart has been a bit outdated.
=> Helm: update sample values file

.github/workflows/helm-release.yaml
The conditionals around git diff weren't working properly.
=> CI: fix generate-chart-schema job

charts/k6-operator/values.schema.json, charts/k6-operator/values.yaml
=> Helm: Enable additionalProperties for global

charts/k6-operator/Chart.yaml, charts/k6-operator/README.md
This is a release with the fix for #528
=> Helm release 3.11.1

.github/workflows/e2e-test.yaml, .github/workflows/golangci-lint.yaml, .github/workflows/helm-lint.yaml, .github/workflows/helm-release.yaml, .github/workflows/helm-test.yaml, .github/workflows/push.yaml, .github/workflows/unit-test.yaml, .github/workflows/yamllint.yaml
After running [zizmor](https://github.com/woodruffw/zizmor) on the main branch (with default setting for now) there were quite a few issues identified. This PR includes fixes for them.
The logic should remain unchanged, hopefully.
Note: this PR also bumps most of the actions used.
=> CI: update all workflows with most of zizmor findings

.github/workflows/e2e-test.yaml, .github/workflows/push.yaml
=> CI: fix wrong commit hash

.github/workflows/e2e-test.yaml, .github/workflows/helm-release.yaml, .github/workflows/push.yaml
=> CI: add necessary permissions

.github/workflows/e2e-test.yaml
=> CI: move e2e workflow to helm/kind-action

pkg/resources/containers/curl_start.go, pkg/resources/containers/curl_stop.go, pkg/resources/jobs/starter.go, pkg/resources/jobs/starter_test.go, pkg/resources/jobs/stopper.go, pkg/resources/jobs/stopper_test.go
This PR will satisfy the feature request made in issue https://github.com/grafana/k6-operator/issues/583
=> enhancement: Allow starter custom resource specifications

pkg/resources/jobs/initializer.go, pkg/resources/jobs/initializer_test.go, pkg/resources/jobs/runner.go, pkg/resources/jobs/runner_test.go
Fixes: https://github.com/grafana/k6-operator/issues/452
=> Change default runner image to grafana/k6:latest

internal/controller/plz_controller.go
When k6-operator is restarted, PLZWorker can become `nil`, which is handled correctly in general case. But if such restart coincides with the removal of PrivateLoadZone, there can be a runtime panic and PLZ is not de-registered properly. This fix improves the logic for that case.
=> Harden logic for the cases when PLZWorker becomes `nil`

CONTRIBUTING.md, Makefile
The output of `make help` now contains the full list of user-facing commands.
=> Improve `make help` command

internal/controller/common.go, internal/controller/k6_create.go, internal/controller/k6_initialize.go, internal/controller/plz_controller.go, internal/controller/testrun_controller.go, pkg/cloud/token.go, pkg/plz/worker.go, pkg/plz/worker_test.go, pkg/resources/jobs/runner.go, pkg/resources/jobs/runner_test.go, pkg/types/k6cli.go, pkg/types/k6cli_test.go
=> Improve security around passing tokens for PLZ tests

docs/maintenance.md, docs/release-workflow.md, docs/releases.md
=> Documentation describing maintenance and releases
