grafana/k6-operator

pkg/resources/jobs/runner.go

This PR adds the `--quiet` as a default argument.
Why? This way we don't have noisy progress bars on the logs.
Closes #5

Make `--quiet` a default argument

---

api/v1alpha1/k6_types.go
config/samples/k6_v1alpha1_k6_with_output.yaml
pkg/resources/jobs/runner.go

- adds a sample manifest with an output as argument
- fixes an issue where arguments where appended as a full string instead of a segmented array

properly append arguments to the run command

---

controllers/k6_start.go

Currently two k6 tests named the same thing in two different namespaces are returned when searching, this breaks the start functionality.
Limit the search for an individual k6 job to the namespace the k6 job was created in.

fix: only search a specific namespace

---

Makefile
api/v1alpha1/k6_types.go
config/crd/bases/k6.io_k6s.yaml
pkg/resources/jobs/runner.go
pkg/resources/jobs/starter.go

Hi everyone,
Currently I'm trying to use the k6-operator to build a chart for load testing on the company I work, in our case we need to set a custom service account name to be used by the job/pod to enable the vault sidecar to inject the volumes on the pod.
Please let me know whether I can improve anything and I'll do it asap!

feat: add support for Service Account Name

---

pkg/resources/jobs/helpers.go
pkg/resources/jobs/helpers_test.go
pkg/resources/jobs/runner.go
pkg/resources/jobs/starter.go
pkg/resources/jobs/starter_test.go

Hi, 
After some testing why the starter pod is always failiing on `0.0.7-rc`. I found my mistake on #56 when running the starter pod. I've replaced the original command `['scuttle', 'sh', '-c']` with `['scuttle', 'k6', '-run']`. This PR will solve this.

Removing the k6 run on the starter pod

---

README.md

cannot install with `github.com/grafana/xk6/cmd/xk6@latest`
replace it with `go.k6.io/xk6/cmd/xk6@latest`
- ref: https://github.com/grafana/k6/issues/1921
- ref2: https://github.com/grafana/xk6#install

docs: update xk6 url in README

---

controllers/k6_start.go

Hello everyone,
We've been using this operator for a while and we observed a strange behavior on tests that took a long time on init phase. We noticed that they remained in "paused state" because the k6 http server was not ready yet. So, we've added a simple verification to make sure the http server is up before sending the start requests to the jobs. It's a simple fix, but the results were very effective.

fix: improve test startup logic

---

config/rbac/role.yaml

After I installed the operator on OpenShift 4.9 cluster, I got the following error after I created a k6 resource:
```
2022-02-19T14:35:11.261Z	INFO	controllers.K6	Creating test jobs	{"k6": "k6-operator-system/k6-sample"}
2022-02-19T14:35:11.261Z	INFO	controllers.K6	Launching k6 test #1	{"k6": "k6-operator-system/k6-sample"}
2022-02-19T14:35:11.266Z	ERROR	controllers.K6	Failed to launch k6 test	{"k6": "k6-operator-system/k6-sample", "error": "jobs.batch \"k6-sample-1\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>"}
github.com/go-logr/zapr.(*zapLogger).Error
```
The serviceaccount requires patch priv on `k6s/finalizers`, added it to RBAC definition.

update clusterrole template to be compatible with OpenShift

---

README.md

Running `docker build -t k6 -f Dockerfile .` with `golang:1.16.4-buster` is throwing an error:
```sh
=> ERROR [builder 3/3] RUN xk6 build --output /k6 --with github.com/szkiba/xk6-prometheus@latest                                                                                                   0.3s
------
> [builder 3/3] RUN xk6 build --output /k6 --with github.com/szkiba/xk6-prometheus@latest:
#10 0.257 2022/05/13 09:54:32 [INFO] Temporary folder: /tmp/buildenv_2022-05-13-0954.394442619
#10 0.257 2022/05/13 09:54:32 [INFO] Initializing Go module
#10 0.257 2022/05/13 09:54:32 [INFO] exec (timeout=10s): /usr/local/go/bin/go mod init k6 
#10 0.261 go: creating new go.mod: module k6
#10 0.263 2022/05/13 09:54:32 [INFO] Pinning versions
#10 0.263 2022/05/13 09:54:32 [INFO] exec (timeout=0s): …
```

Minor change on README

---

api/v1alpha1/k6_types.go
config/crd/bases/k6.io_k6s.yaml
pkg/resources/jobs/runner.go
pkg/resources/jobs/runner_test.go

Closes https://github.com/grafana/k6-operator/issues/122.

feat: ability to set the environment variables with envFrom in k6 runner/starter.

---

controllers/k6_start.go

Uses the Cluster IP to connect to services instead of the service name. Credits to @pekavau for finding the issue and workaround.
fixes  #132

Fix: use Cluster IP instead of service name

---

Dockerfile.controller
Makefile

This PR adds the ability to build the go app using a custom Go builder image. I use it to be able to build the operator in a corp network.

Be able to use a custom Go image to build apps

---

README.md
config/samples/k6_v1alpha1_k6_with_volumeClaim.yaml

* Adds a volumeClaim example: `config/samples/k6_v1alpha1_k6_with_volumeClaim.yaml`.
* Updates the readme with a more thorough explanation on how to use volumeClaims and also adds a directory example.
* After taking some time debugging and experimenting with running k6 tests using volumeClaims, I believe having more concrete examples and explanations like this would help folks working with it in the future.

Updates README and adds an example for volumeClaim testing usage

---

controllers/k6_initialize.go

Signed-off-by: Marcos Candeia <marrcooos@gmail.com>
See #164

Specify k6 container when reading logs

---

pkg/resources/jobs/initializer.go
pkg/resources/jobs/initializer_test.go

Thanks to the awesome investigation/write-up by @mcandeia, this update no longer copies annotations from the runner specification. Each runner pod will still receive annotations as desired. If annotations support in initializer pod is desired, we'll probably need to incorporate an `Initializer Pod` entry within the [`K6Spec`](https://github.com/grafana/k6-operator/blob/main/api/v1alpha1/k6_types.go#L63-L64).
Signed-off-by: javaducky <javaducky@gmail.com>
Fixes #164

Do not add annotations to initializer based upon runner specification

---

pkg/resources/jobs/runner.go
pkg/resources/jobs/runner_test.go

Hi,
this PR fixes scheduling of starter-Pod when using `spec.separater=true` by adding `runner=true` to matched Label-Expressions in podAntiAffinity.
Fixes #168

Add runner=true label to matchedExpressions in podAntiAffinity

---

pkg/resources/jobs/initializer.go
pkg/resources/jobs/initializer_test.go

This PR adds a CLI workaround for initializer pod so that it terminates with error exit code and error log line in case of errors logged by k6. Initializer pod is to be started only once: if there's an error from k6, then the script or setup requires fixes. Otherwise, initializer logs the JSON output of `inspect` command and terminates with zero exit code.
Fixes #167

Improve initializer logs on k6 errors

---

pkg/cloud/cloud.go

While running some tests the initializer couldn't marshal the full threshold syntax.
Threshold syntax is [docs](https://k6.io/docs/using-k6/thresholds/#threshold-syntax):
```
export const options = {
thresholds: {
metric_name1: ['threshold_expression', `...`], // short format
metric_name2: [
{
threshold: 'threshold_expression',
abortOnFail: true, // boolean
delayAbortEval: '10s', // string
},
], // full format
},
};
```
This adds support for full and short versions of thresholds using `stats.Thresholds`

Adds support for full threshold syntax

---

api/v1alpha1/k6_types.go
api/v1alpha1/zz_generated.deepcopy.go
config/crd/bases/k6.io_k6s.yaml
pkg/resources/jobs/helpers.go
pkg/resources/jobs/helpers_test.go

Scuttle logging is enabled by default:
https://github.com/redboxllc/scuttle/blob/1c2b697935c10ef4b3e5e0dc0cf573a4d8766269/scuttle_config.go#L31
So the setting for it should be "disable logging" instead of "enable logging" as it has been so far.
This is a breaking change for those who rely on `scuttle` configuration.
This PR also contains cleaned up manifests (after `make manifests`) as it appears some of previous changes weren't properly applied before.

Scuttle config: change scuttleLogging to disableLogging

---

pkg/resources/jobs/runner.go
pkg/resources/jobs/runner_test.go

As discussed in https://github.com/grafana/k6-operator/pull/169#discussion_r1073534803, I open in a separate PR this new feature.

Allow liveness and readiness probes for runner pods

---

docs/versioning.md

It's not always clear what version of k6 is being run when using a default runner's image. Let's keep this info in a table for now, to have it easily accessible.

Docs to clarify versioning in runner

---

pkg/resources/jobs/initializer.go
pkg/resources/jobs/initializer_test.go

for https://github.com/grafana/k6-operator/issues/210

Assigning securityContext in k6 initializer

---

api/v1alpha1/conditions.go
api/v1alpha1/k6_types.go
config/crd/bases/k6.io_k6s.yaml
controllers/k6_initialize.go
pkg/cloud/aggregation.go
pkg/cloud/cloud.go
pkg/resources/jobs/runner.go
pkg/resources/jobs/runner_test.go

Fixing #228 
This branch with env vars for aggregation was already on my local so pushing it here.
Adding the env vars to the runners like this is a workaround which is not a good solution. This shouldn't be fixed on k6-operator side: it should be fixed on k6 side by making aggregation turned on by default, at least in case of `-out cloud` option.
@esquonk, please check if the numbers are correct: if they are, I'll merge it in the evening and make a release.
Related issue: #192

Set k6 env vars for metrics aggregation by default for cloud output

---

pkg/resources/jobs/initializer.go
pkg/resources/jobs/initializer_test.go

This pr creates a directory where js test file is located to fix an issue when js test file is stored in volume (PVC/PV resources).
- create k6 CRD resource
```
apiVersion: k6.io/v1alpha1
kind: K6
metadata:
name: test
spec:
arguments: --vus 1 --iteration 1
parallelism: 1
runner:
image: ...
script:
volumeClaim:
file: some-dir/1/test.js
name: k6-pvc
scuttle:
enabled: "false"
```
Initializer pod will be failed with `no such file or directory` error while trying to run:
```
k6 archive some-dir/1/test.js -O /tmp/some-dir/1/test.js.archived.tar ...
```
Because the `/tmp/some-dir/1/` directory doesn't exist

Fix 'no such file or directory' issue in initializer

---

README.md

Fix up the JS example in the README
- `-` in the middle of a variable name is not valid in nearly all programming languages, including [JS](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#variables)
- use conventional JS camelCase (instead of invalid kebab-case)
- fix comment headings -- the first file is `test.js`, the second file is `stress-test.js`
- can't both be `stress-test.js` 😅
- use `const` instead of `let` for options
- consistent with [k6 docs](https://github.com/grafana/k6/blob/a2fe0a8e824423262e7029c3853dc0fa5ce9f9b6/README.md?plain=1#L48)
- consistently use 2 space indentation
- same as the rest of this file
- add new lines between code blocks
- consistent with the rest of this file (and easier on the eyes + passes `markdownlint`)

fix(docs): use valid, conventional syntax in JS example

---

README.md

Improve syntax highlighting in the README
- 2 code blocks that were missing highlighting
- 1 of the blocks was incorrectly labeled as `bash` instead of `yaml` syntax
- also comment out all ellipses ("...") in code blocks
- for more valid sample code that can be more easily copy+pasted

docs: add missing YAML syntax highlighting

---

README.md

This also includes minor updates for consistent usage on terminal examples and add prerequisites for installation.
Fixes #181

Updating example when building with extensions

---

controllers/k6_initialize.go
pkg/cloud/cloud_output.go

Logic around test names in case of cloud output now corresponds to default in k6. It's also more straight-forward overall.

Fix default name of test runs in cloud output

---

.github/workflows/e2e-test.yaml

`buildx` version was pinned only in push workflow so images built during e2e workflow have been Linux-only.

Fix builx version in e2e workflow

---

config/manifests/bases/k6-operator.clusterserviceversion.yaml

This PR fixes operator-sdk bundle validation.

Fix CSV to include both CRDs

---

api/v1alpha1/k6_types.go
config/crd/bases/k6.io_k6s.yaml

As it was exposed [here](https://github.com/grafana/k6-operator/issues/206), `nodeselector` uses wrong notation and breaks with Kubernetes standard naming. This PR renames the section to `nodeSelector`
**This is a breaking change**, if you want to maintain backward compatibility, I can update the PR adding support to both and a deprecation message on the wrong one
Fixes https://github.com/grafana/k6-operator/issues/206

fix: Use standard naming for nodeSelector definition

---

pkg/cloud/aggregation.go
pkg/cloud/aggregation_test.go

This change is meant to be backwards compatible: i.e. if someone has resources created with cloud output v1 vars, they'll be decoded correctly. But all new resources are to be created with cloud output v2.
Config reference:
https://github.com/grafana/k6/pull/3092/commits/3e43e15e0bfac2e1b467605df4a8dccd78b9ad2c

Switch to cloud output v2

---

.github/workflows/e2e-test.yaml

Fixes #311 
https://github.com/grafana/k6-operator/actions/runs/6512492225/job/17690286747
```
Run helm/kind-action@v1.2.0
with:
node_image: kindest/node:v1.27.1
Installing kind...
Adding kind directory to PATH...
Installing kubectl...
Adding kubectl directory to PATH...
kind v0.11.1
```
The log said that we use the old `kind` despite `kindest/node` is newer one.
It can be fixed to select the old kindest/node version.
https://github.com/helm/kind-action/blob/v1.2.0/action.yml#L12-L13

ci: add node_image version to kind-action

---

.github/workflows/helm-release.yaml

PR to helm-charts was merged in: https://github.com/grafana/helm-charts/pull/2728
Updating CI to use `main` branch.

CI: use main branch of helm-charts

---

.github/workflows/golangci-lint.yaml
Makefile
controllers/k6_controller.go
controllers/k6_initialize.go
controllers/k6_stopped_jobs.go
controllers/testrun_controller.go
main.go
pkg/resources/jobs/helpers.go
pkg/resources/jobs/runner.go
pkg/types/conditions.go
pkg/types/k6cli.go

Fixes #157 
Add golangci-lint on github actions ci and fixed some conventional issues of linting.

ci: add golang lint and fixed. #157

---

.github/workflows/e2e-test.yaml
Makefile
config/crd/bases/k6.io_k6s.yaml
config/crd/bases/k6.io_privateloadzones.yaml
config/crd/bases/k6.io_testruns.yaml
config/rbac/role.yaml

Fixes: https://github.com/grafana/k6-operator/issues/273
After going through the changelog of controller-gen; we don't have any breaking changes other than `trivialVersions` option. That option appeared during "volumes in init containers" addition, to limit the size of CRD. But with update of controller-gen to v0.13.0, just passing `maxDescLen=0` appears to be sufficient to achieve the same goal.

Update controller-gen to v0.13.0

---

.github/workflows/helm-lint.yaml

On releases `ct lint` fails to find a git tag:
Probably because the tag doesn't exist at that point yet. We don't exactly require this workflow for release as it's sufficient to run it on main branch. So limiting this GA to branches only.

CI: limit Helm linting to branches only

---

charts/k6-operator/Chart.yaml
charts/k6-operator/samples/customAnnotationsAndLabels.yaml
charts/k6-operator/templates/_helpers.tpl
charts/k6-operator/templates/deployment.yaml
charts/k6-operator/values.yaml

Hey, we leverage tooling that requires certain labels to be present. While deploying into our ecosystem I noticed the pods don't have the capability to have custom labels. This PR is meant to include that annotation and feature for others that require specific pods labels

Enable custom pod labels for helm chart

---

charts/k6-operator/Chart.yaml
charts/k6-operator/README.md
charts/k6-operator/templates/crds/k6.yaml
charts/k6-operator/templates/crds/plz.yaml
charts/k6-operator/templates/crds/testrun.yaml
charts/k6-operator/values.yaml

feat: optional installation of crds

---

charts/k6-operator/templates/deployment.yaml
charts/k6-operator/templates/prometheus/serviceMonitor.yaml

Fixes #324 where helm install with flag `--set prometheus.enabled=true` fails unless the `system` namespace exists.  Set this to the same namespace as all the other resources installed via the chart. Additionally, restrict the namespace selector to be within the same namespace as well so there is chance of accidental cross namespace lookup and drag in another service by chance.
Furthermore, fixes the selector label on the service itself as the current select 
```yaml
selector:
control-plane: "controller-manager"
```
points to nothing. This can be easily verified without the need of a `ServiceMonitor` by port forwarding to the service and perform a simply curl against the endpoint. The change is to use the `selectorLabels` that is used under `.spec.template.metadata.labels` in the …

fix issue with service monitor

---

pkg/resources/jobs/initializer.go
pkg/resources/jobs/initializer_test.go

As discussed, this is a very small PR adding the `envFrom` field for initializer and should fix #348 
This is my first time going through the k6-operator source code so if I missed anything (helm chart version bump or test cases in `initializer_test.go`) then let me know.

feat: add initializer envFrom field

---

Dockerfile.controller
Dockerfile.starter

- user nonroot/root may not work in some k8s environments.
- k8s domain may differ from `cluster.local`.

Fix dockerfile user and remove k8s cluster domain suffix from status url

---

api/v1alpha1/k6conditions.go
api/v1alpha1/testruni.go
controllers/common.go
controllers/k6_start.go
controllers/k6_stopped_jobs.go
controllers/testrun_controller.go
pkg/resources/jobs/runner.go
pkg/resources/jobs/runner_test.go
pkg/testrun/k6client.go
pkg/types/conditions.go
pkg/types/k6status.go

Issue: #223 
This PR implements the necessary logic **only for PLZ test runs**, thus leaving all other test runs as they have been executed so far.
Rationale: for a general case of OSS distributed test run, this logic is rather convoluted and implementing it in full would require to rather drastically intrude into standard logic of Kubernetes Job controller. From the design perspective, it would be preferable to implement full solution for `setup` and `teardown` via native distributed mode in k6 instead. Once that happens, PLZ test runs could also switch to using the logic of k6 distributed mode.

Call `setup` and `teardown` only once for PLZ

---

docs/env-vars.md
docs/troublehooting.md

This is initial version for troubleshooting guide, issue: #331 
It is expected to be iteratively improved in the future.

Adding troubleshooting guide

---

charts/k6-operator/templates/deployment.yaml
charts/k6-operator/values.yaml

I used the [grafana-agent](https://github.com/grafana/agent/tree/main/operations/helm/charts/grafana-agent) helm chart as a rough reference. Happy to tweak any of the value names or descriptions. Thank you!

adds global registry and imagepullsecrets override to helm chart

---

config/samples/k6_v1alpha1_k6_with_initContainers.yaml
pkg/resources/jobs/helpers.go
pkg/resources/jobs/initializer.go
pkg/resources/jobs/runner.go

Fixes [296](https://github.com/grafana/k6-operator/issues/296)
Enables you to have separate initContainers for the initializer and runner pod. 
Was tested successfully in own K8 environment (only the initializer pod was configured to have initContainers):
Config looks like this:
```yaml
initializer:
...
{{- if .Values.executor.script.volumeClaim }}
initContainers:
- image: {{ tpl $.Values.docker.registry $ }}/{{ tpl $.Values.image.name $ }}:{{ tpl $.Values.image.tag $ }}
{{- if .Values.image.command }}
command: [ "sh", "-c", {{ .Values.image.command }} ]
{{- else }}
{{- with (index .Values.mount.pvcs 0) }}
command: [ "sh", "-c", "cp -r /home/* {{ .path }};" ]
{{- end }}
{{- end }}
{{- end }}
```

feat: differentiate between Runner and Initializer initContainers

---

.github/workflows/golangci-lint.yaml
.github/workflows/unit-test.yaml
Makefile

Recent change in envtest is causing CI to break:
https://github.com/kubernetes-sigs/controller-runtime/issues/2720
So fixing envtest version for now.
+ Minor update of `go-version`.

Fix envtest runs in CI

---

.github/workflows/push.yaml
Dockerfile.controller
Dockerfile.runner
Dockerfile.starter

solves https://github.com/grafana/k6-operator/issues/187
Pls make any changes if required.

Add arm64 support

---

README.md
docs/env-vars.md

Adding some clarifications in docs for: 
- `WATCH_NAMESPACE` env var
- Helm documentation
- highlighting recommended practice for env vars in k6 scripts

Docs: add missing details

---

controllers/common.go
controllers/k6_initialize.go

PullRequest 291 has been out of date, and I believe that more time has passed and merging has become more difficult, so I have reworked the PR.
The changes are basically the same as in PullRequest 291, with a few modifications based on comments.
https://github.com/grafana/k6-operator/pull/291
Thanks to JorTurFer and yorugac.

Treat failed initializer as error (PR 291 continued)

---

.github/workflows/helm-lint.yaml
.github/workflows/helm-test.yaml

Enable Helm lint and test workflow on PRs, except for automated bundle update.

CI: run Helm lint and test on PRs

---

.github/workflows/e2e-test.yaml

E2E workflow has been broken for the last few weeks.
Why: https://github.com/karancode/kustomize-github-action/issues/46
Adding token as a workaround, found by nice folk in the above issue.
~~If~~ When there's a proper fix for kustomize GA, token here should be removed.

CI: add token to bypass bug in kustomize GA

---

config/samples/k6_v1alpha1_k6.yaml
config/samples/k6_v1alpha1_k6_with_initContainers.yaml

As noticed in community forum, we have some outdated samples still.
Ref.: https://community.grafana.com/t/k6-custom-resource-kind-testrun-vs-k6/123965

Docs: update samples to use TestRun instead of K6

---

api/v1alpha1/k6_types.go
api/v1alpha1/testrun_types.go
config/crd/bases/k6.io_k6s.yaml
config/crd/bases/k6.io_testruns.yaml
config/samples/k6_v1alpha1_k6_with_readOnlyVolumeClaim.yaml
pkg/types/script.go

Added ReadOnly to the volumeMount option in Pods to support mounting of ReadOnlyMany(ROX) PVC.
https://github.com/grafana/k6-operator/issues/279
The default is ReadOnly: false.
The reason was to avoid destructive changes, considering the possibility that some users may already be writing to the volume in the init container.
Here are the results of a simple test.
[files.zip](https://github.com/user-attachments/files/15799552/files.zip)
Test Contents
- kubectl apply -f pvc.yaml to create pods to add pods and scenarios
- kubectl exec -it vp -- /bin/bash to add main.js to /mnt/vp in pods
- Create TestRun with kubectl apply -f main.yaml
result
describe-log.txt and get-log.txt are the execution results.
You can confirm that ReadOnly for k6-test-volume is true.

Add ReadOnly option to volumeMount in Pods

---

pkg/cloud/types.go

A fix mainly for unit tests, in order not to depend on maps being passed without order. Now env vars in spec are being sorted by name of an env var.

PLZ: add deterministic order of env vars

---

.github/workflows/helm-release.yaml
Makefile
charts/k6-operator/values.schema.json
charts/k6-operator/values.yaml

closes #431
Adds initial `schema.values.json` to the chart and extends `helm-release` with a step that generates and commits the schema.
Also, adds a new Makefile target to generate the schema using [github.com/dadav/helm-schema](github.com/dadav/helm-schema).

generate helm values schema

---

.github/workflows/helm-lint.yaml
.github/workflows/helm-test.yaml

Attempt to fix the issue: https://github.com/grafana/k6-operator/issues/419

CI: simplify helm workflows

---

.github/workflows/helm-test.yaml

Related issue: https://github.com/grafana/k6-operator/issues/419

CI: fix `ct install` in helm-test

---

e2e/ipv6/kind-ipv6.yaml
pkg/resources/containers/curl_start.go
pkg/resources/containers/curl_stop.go

**Summary**
Bug Fixed: [Starter doesn't work in an IPv6 cluster](https://github.com/grafana/k6-operator/issues/171)
This pull request addresses the IPv6 compatibility issue in the k6-operator as outlined in the referenced issue. Specifically, the changes ensure that the k6-curl container can correctly handle IPv6 addresses.
**Changes Made**
Introduced the net package to handle IPv6 addresses.
Hostname Wrapping: Utilized net.JoinHostPort to wrap the hostname in square brackets if it is a literal IPv6 address, ensuring proper formatting.
**Testing**
Verified that the k6-curl container now supports both IPv6 and IPv4 addresses.
Conducted tests on local k8s cluster via KIND to confirm the functionality of the k6 operator with the updated IPv6 support.
Snapshot of starter pod that deals with …

Fix IPv6 compatibility issue with starter pod

---

controllers/plz_controller.go
controllers/plz_factory.go
pkg/testrun/plz.go
pkg/testrun/plz_test.go

This is likely a temporary solution that will be removed once k6 supports cloud logs for local execution natively, reference issue:
https://github.com/grafana/k6/issues/3282

Add cloud logs configuration to PLZ test runs by default 

---

controllers/common.go

Relates to https://github.com/grafana/k6-operator/pull/453

Fix typo in variable containing error when fetching pod logs

---

controllers/common.go

Fixes: https://github.com/grafana/k6-operator/issues/456

Propagate error on copying logs from initializer

---

charts/k6-operator/templates/deployment.yaml
charts/k6-operator/values.schema.json
charts/k6-operator/values.yaml

With 3.9.0, the `values.schema.json` is created incorrectly from the `values.yaml`, therefore not allowing any extra env values from `manager.env` to be placed in there since it's requiring an object, but `env` is supposed to be an array of objects.
Should fix https://github.com/grafana/k6-operator/issues/471

Fixing values.yaml docs for schema generation, corrected values.schema.json

---

.github/workflows/helm-release.yaml

Release workflow gets the startup failure:
```
Invalid workflow file: .github/workflows/helm-release.yaml#L47
The workflow is not valid. .github/workflows/helm-release.yaml (Line: 47, Col: 3): Error calling workflow 'grafana/helm-charts/.github/workflows/update-helm-repo.yaml@main'. The nested job 'release' is requesting 'packages: write', but is only allowed 'packages: none'.
```
Failed build: https://github.com/grafana/k6-operator/actions/runs/11628556424
Permissions are being set in the helm-charts workflow:
https://github.com/grafana/helm-charts/blob/main/.github/workflows/update-helm-repo.yaml#L96
Not certain if there could there be a conflict between the two, but it doesn't make sense to set them from the calling workflow.

CI: remove permissions from the call to helm-charts

---

pkg/cloud/types.go

Not all run statuses from GCk6 that should case an abort were accounted for, which caused a rare but unpleasant bug.

Cloud: abort on timeout run status

---

.github/workflows/push.yaml

This reverts commit b8e6e3438701d4c7b280fd10b6d5fcb01aa3038e.

Revert "CI: allow bundle generation for manual dispatch"

---

charts/k6-operator/Chart.yaml
charts/k6-operator/README.md

We were having issues with the release as a consequence of trying to fix OCI changes in helm-charts. For ref.:
https://github.com/grafana/helm-charts/pull/3424
Bumping a chart as a test.

Release Chart 3.10.1

---

.github/workflows/helm-lint.yaml
.github/workflows/helm-test.yaml

Default ubuntu-latest runner is being bumped to 24.04:
https://github.com/actions/runner-images/issues/10636
And apparently Python should be recent enough to be installed there:
https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
CI error:

CI: bump python version for helm workflows

---

charts/k6-operator/Chart.yaml
charts/k6-operator/README.md
charts/k6-operator/values.schema.json
charts/k6-operator/values.yaml

Issue: https://github.com/grafana/k6-operator/issues/515

Helm: fix schema to allow name overrides and release 3.10.2

---

README.md

Fixes https://github.com/grafana/k6-operator/issues/550.

Remove outdated blog post link from README

---

.github/zizmor.yml

Related: PR #559 
New automated workflow for zizmor is here: https://github.com/grafana/security-github-actions/blob/main/.github/workflows/self-zizmor.yaml

CI: add zizmor.yml to ignore cache-poisoning

---

charts/k6-operator/templates/service.yaml
charts/k6-operator/values.schema.json
charts/k6-operator/values.yaml

I want to be able to access the service without using the authproxy.
Moreover I added the way to put some custom labels and annotations on it

feat: allow service without authproxy

---

.github/workflows/helm-release.yaml

Following the guide:
https://github.com/grafana/shared-workflows/tree/main/actions/get-vault-secrets

CI: update helm release to use vault

---

api/v1alpha1/privateloadzone_types.go
charts/k6-operator/templates/crds/plz.yaml
config/crd/bases/k6.io_privateloadzones.yaml

For some reason, the default `age` column disappeared with the changes in https://github.com/grafana/k6-operator/pull/558 so it's not so "default". Adding it back manually.
Issue: https://github.com/grafana/k6-operator/issues/524

Fix PLZ printer columns to have `age`

---

charts/k6-operator/templates/clusterRole.yaml
charts/k6-operator/templates/clusterRoleBinding.yaml
charts/k6-operator/values.schema.json
charts/k6-operator/values.yaml

This change provides a value for guarding the creation of cluster roles and role bindings. For shared clusters with multiple namespaces, it may not be possible for someone to create cluster-level roles. More details in https://github.com/grafana/k6-operator/issues/574.
In such a case, in their Helm chart, they would set ...
```
"installClusterRBAC": false
```
and then manage the roles and role bindings themselves.
The alternative is to allow creating these cluster RBACs and namespaced RBACs instead.

Add rbac.namespaced value as an option to disable creation of cluster roles and role bindings

---

.github/workflows/e2e-test.yaml

In e2e-test workflow and release workflow, there were two different kustomize actions being used. Unifying it now to use just one (the most recently updated one, though that might need a second look later).

chore(ci): use only `setup-kustomize` for kustomize

---

charts/k6-operator/README.md
charts/k6-operator/samples/customAnnotationsAndLabels.yaml
charts/k6-operator/templates/_helpers.tpl
charts/k6-operator/templates/clusterRole.yaml
charts/k6-operator/templates/clusterRoleBinding.yaml
charts/k6-operator/templates/crds/testrun.yaml
charts/k6-operator/templates/deployment.yaml
charts/k6-operator/templates/role.yaml
charts/k6-operator/templates/service.yaml
charts/k6-operator/values.schema.json
charts/k6-operator/values.yaml

Issue: https://github.com/grafana/k6-operator/issues/235
This is a follow-up on PR https://github.com/grafana/k6-operator/pull/512, to ensure that Helm chart is fully up-to-date with those changes and can be upgraded successfully.

Update Helm chart according to the latest kubebuilder changes

---

charts/k6-operator/templates/deployment.yaml
config/manager/manager.yaml

Only binding the metrics server to the IPv4 loopback adapter makes it impossible to scrape these metrics from outside of the controller pod.

Bind metrics server on all interfaces by default, not just loopback

---

charts/k6-operator/Chart.yaml
charts/k6-operator/README.md
charts/k6-operator/templates/deployment.yaml

Fixes: https://github.com/grafana/k6-operator/issues/596

Helm 3.14.2: 8443 port as a default for manager metrics

---

.gitignore
e2e/README.md
e2e/latest/ClusterRole-k6-operator-metrics-auth-role.yml
e2e/latest/ClusterRoleBinding-k6-operator-manager-rolebinding.yml
e2e/latest/ClusterRoleBinding-k6-operator-metrics-auth-rolebinding.yml
e2e/latest/Deployment-k6-operator-controller-manager.yml
e2e/latest/Namespace-k6-operator-system.yml
e2e/latest/Role-k6-operator-leader-election-role.yml
e2e/latest/RoleBinding-k6-operator-leader-election-rolebinding.yml
e2e/latest/Service-k6-operator-controller-manager-metrics-service.yml
e2e/latest/ServiceAccount-k6-operator-controller.yml
e2e/latest/kustomization.yaml
e2e/run-tests.sh

- id of the user is looked up with `id` command (for docker execution)
- addition of `-u` flag to update the manifests in `latest` without running the tests
- typos in Readme
- update of manifests in `latest`
- early sanity check if the configured Docker image exists prior to running the tests

 `e2e` suite: small fixes and improvements and update of the default manifests

---

api/v1alpha1/privateloadzone_types.go
config/crd/bases/k6.io_privateloadzones.yaml
docs/crd-generated.md

This is a requirement for Grafana Cloud k6 [UI tests](https://grafana.com/docs/grafana-cloud/testing/k6/author-run/script-editor/).
The value of the default is still true, it's `grafana/k6:latest`, but the default image for PLZ tests must be set by GCk6 side; otherwise, UI test cannot be started.

Remove default image from PLZ definition

---

e2e/README.md
e2e/run-tests.sh

2 small changes:
- removing Docker image check from the script.
- adding shortcut command for quickly loading `.env` files to Readme.

Small fixes for e2e test suite

---

charts/k6-operator/README.md
charts/k6-operator/templates/deployment.yaml
charts/k6-operator/templates/service.yaml
charts/k6-operator/values.schema.json
charts/k6-operator/values.yaml

Adds a `portName` option to the Helm chart so that the Deployment and Service port name can be configured externally.

Add `portName` option to Helm chart
